name       : perl-text-glob
version    : '0.11'
release    : 10
source     :
    - https://cpan.metacpan.org/authors/id/R/RC/RCLAMP/Text-Glob-0.11.tar.gz : 069ccd49d3f0a2dedb115f4bdc9fbac07a83592840953d1fcdfc39eb9d305287
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : match globbing patterns against text
description: |
    match globbing patterns against text
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
