name       : perl-text-glob
version    : 0.10
release    : 1
source     :
    - http://search.cpan.org/CPAN/authors/id/R/RC/RCLAMP/Text-Glob-0.10.tar.gz : d0af0549a9dd1c70edcd3b1429ccc3702b79b873375b79cd2bdfe8870e337449
license    : GPL-2.0
component  : programming.perl
summary    : match globbing patterns against text
description: |
    match globbing patterns against text
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
